// #include<bits/stdc++.h>
// using namespace std;

// int main(){
//     map<int,string>m;
// //inserting elemnt in map
//     m[1]="abc";
//     m[5]="bcd";
//     m[2]="bgd";
// // another way of inserting elemnts in map
// m.insert({3,"khg"});
// m.insert({9,"kdg"});
// /*
// //printing map method-1
// map<int,string>:: iterator it;
// for(it=m.begin();it!=m.end();++it){   // here m.begin()->first elment int the iterator and m.end()->last iterator ka next iterator
//     cout<<(*it).first<<" "<<(*it).second<<endl;   // (*it) is for taking value
// }*/

// // printing map method-2
// for(auto &pr:m ){
//     cout<< pr.first<< " "<< pr.second<<endl;
// }


// }

// //OUTPUT  map always prints i sorted order of key
// // 1 abc
// // 2 bgd
// // 3 khg
// // 5 bcd
// // 9 kdg
 